sudo: required
services:
  - docker

before_install:
  - docker build -t defudef/simple-react -f Dockerfile.dev .

script:
  - docker run -e CI=true defudef/simple-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-fun"
  env: "DockerFun-env"
  bucket_name: "elasticbeanstalk-us-east-2-741205034335"
  bucket_path: "docker-fun"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"